name: build-and-deploy
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - 'Herm71/issue3'
permissions:
  contents: write
jobs:
  build-branch:
    name: Build branch
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from branch
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: branch-build
        path: dist
    - uses: technote-space/workflow-conclusion-action@v1
      with:
        status: ${{ env.WORKFLOW_CONCLUSION }}
  release-branch:
    name: Release branch
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    needs: build-branch
    steps:
    - name: Checkout code from gh-pages branch
      uses: actions/checkout@v3
      with: 
        ref: gh-pages
    - name: Check branch and status
      run: git branch && git status && ls -R
    - name: After checkout clean branch
      run: rm -rf * && ls -R
    - name: Download latest build
      uses: actions/download-artifact@v3
      with:
        name: branch-build
        path: build
    - name: Copy files from build to root and delete build dir
      run: cp -R ./build/* . &&  rm -rf ./build
    - name: Check git branch and status
      run: git branch && git status
    
  