name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - 'Herm71/issue3'
permissions:
  contents: write
jobs:
  copy-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
           name: test-build
           path: dist/*
      - uses: actions/checkout@v3
        with:
          ref: test
      - uses: actions/download-artifact@v3
        with:
          name: test-build
    
      - name: Display structure of downloaded files
        run: ls -R
      
    