name: deploy-artifact
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - 'Herm71/issue3'
permissions:
  contents: write
jobs:
  build-branch:
    name: Build branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from branch
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: branch-build
        path: dist
    - uses: technote-space/workflow-conclusion-action@v1
      with:
        status: ${{ env.WORKFLOW_CONCLUSION }}
  release-branch:
    name: Release branch
    runs-on: ubuntu-latest
    needs: build-branch
    env:
        SRC_FOLDER_PATH: './build'
        TARGET_BRANCH: 'test'
    steps:
    - name: Checkout code from test branch
      uses: actions/checkout@v3
      with: 
        ref: $TARGET_BRANCH
    - name: Post checkout clean
      run: rm -rf * && ls -R
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: branch-build
        path: $SRC_FOLDER_PATH
    - name: Test arifact download
      run: ls -R
    - name: Copy files from download to root
      run: cp -R $SRC_FOLDER_PATH/* . &&  rm -rf $SRC_FOLDER_PATH && ls -R
    - name: Git branch and status
      run: git branch && git status
    - name: Git add files and status
      run: git add . && git status
    - name: Git commit  and status
      run: git commit -m "test build update" && git status
    - name: Git push
      run: git push origin test

    