name: deploy-artifact
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - 'Herm71/issue3'
permissions:
  contents: write
jobs:
  build-branch:
    name: Build branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from branch
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: branch-build
        path: dist
    - uses: technote-space/workflow-conclusion-action@v1
      with:
        status: ${{ env.WORKFLOW_CONCLUSION }}
  release-branch:
    name: Release branch
    runs-on: ubuntu-latest
    needs: build-branch
    steps:
    - name: Checkout code from test branch
      uses: actions/checkout@v3
      with: 
        ref: test
    - name: After checkout clean branch
      run: rm -rf * && ls -R
    - name: Download latest build
      uses: actions/download-artifact@v3
      with:
        name: branch-build
        path: build
    - name: Copy files from build to root and delete build dir
      run: cp -R ./build/* . &&  rm -rf ./build
    - name: Check git branch and status
      run: git branch && git status
    - name: Git add files, commit and push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
        git push origin test

    